CC=gcc 
CFLAGS=
DEPS = server_includes.h LL_queue.h 				    # include directory
OBJ = game_server.o 								 	# source directory

%.o: %.c $(DEPS) 										# create .o files after compiling .c and .h files
	$(CC) -c -o $@ $< $(CFLAGS)

game_server: $(OBJ) 											# create out file
	$(CC) -o $@ $^ $(CFLAGS) 
