CC=gcc 
CFLAGS=
DEPS = client_includes.h                                # include directory
OBJ = game_client.o                                     # source directory

%.o: %.c $(DEPS) 										# create .o files after compiling .c and .h files
	$(CC) -c -o $@ $< $(CFLAGS)

game_client: $(OBJ) 											# create out file
	$(CC) -o $@ $^ $(CFLAGS) 
